server:
  port: 8083

spring:
  application:
    name: pedidos-service
  datasource:
    url: jdbc:h2:mem:pedidos-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true

rabbitmq:
  queues:
    - pedido.almoxarifado
    - pedido.transporte

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html